#!/bin/bash

echo "🎨 Laravel Pint ile kod formatlanıyor..."
files=$(git diff --cached --name-only --diff-filter=ACM -- '*.php');
vendor/bin/pint $files -q

git add $files

echo "✅ Kod başarıyla formatlandı."
